### ISSUE TITLE
How to create a archives page with pagination like author's blog？

### ISSUE THREAD

**Issue by tocer01** [carsonip/hugo-theme-minos#10]
Thanks for such elegant theme :) I'm a new person to github and want to ask author a questoin.  In author's [blog](http://blog.zhangruipeng.me/hexo-theme-minos/archives/), there is a `arvhices` page **with pagination**.

In my situation, I put all posts into a directory whose name is `archives`, however there is no pagination in `/archives` page. **But there is pagination in `/` page**.

So how can I make pagination in `/archives` page.

**Comment by carsonip** [comment]
There should be pagination. Also, I have discovered a bug in the implementation and have fixed it in c309cdb1fd6747507760285b1fc868b32538fe21. Make sure your `paginate` under `config.toml` is set correctly. Please try the new version of the theme and let me know if it works. Thanks!

**Comment by carsonip** [comment]
Also please update your hugo. I am using v0.21 and everything is working well.
