### ISSUE TITLE
不支持归档页吗？

### ISSUE THREAD

**Issue by hijulian** [carsonip/hugo-theme-minos#13]

**Comment by carsonip** [comment]
Sorry for the late reply. What do you mean by 归档页? Is there an example? Although I understand Chinese, please try to use English on Github, otherwise people may get confused.

**Comment by hijulian** [comment]
How to add an archive page？

**Comment by carsonip** [comment]
There is no archive page built into this theme as this is just a simple port of the original Hexo theme. Here is a tutorial of how to add an archive page to a Hugo theme by yourself:
https://parsiya.net/blog/2016-02-14-archive-page-in-hugo/
PR is always welcomed.
