### ISSUE TITLE
Footnotes shown in excerpt on mainpage

### ISSUE THREAD

**Issue by mdosch** [carsonip/hugo-theme-minos#14]
When using footnotes they are shown in the excerpt on the mainpage although the link leads to nowhere.
For example see  https://blog.mdosch.de in the excerpts for the posts on 2018-05-09 and  2018-05-08.

Also sometimes links are in the excerpt, sometimes not. Don't know if these are theme issues or hugo issues but I guess the creation of the mainpage is defined in the theme.

**Comment by carsonip** [comment]
Nice find. I haven't worked on this theme for a while. Let me check if this is hugo's problem or the theme's problem. My bet is on hugo's because there's no special handling for footnotes.

**Comment by carsonip** [comment]
I don't even see a link on the mainpage. I tried with the hyde theme and it behaves the same. In the code we simply use `{{ .Summary }}` to display the summary. That's why I suppose it is not a problem specific to this theme. Maybe you could create an issue under the hugo repo.
