### ISSUE TITLE
Pagination: current site not shown on mobile view

### ISSUE THREAD

**Issue by mdosch** [carsonip/hugo-theme-minos#15]
In the pagination the current page is "highlighted" with a circle but when you make your browser window very small or open the site from mobile the circle and the page number disappear. You can also see this in your [demo](https://themes.gohugo.io/theme/hugo-theme-minos/).

**Comment by carsonip** [comment]
Thanks for pointing this out. I can reproduce it. Let me fix this by weekend.

**Comment by carsonip** [comment]
Looking at style.css:788, there's something like this:
```
@media screen and (max-width: 839px)
#page-nav .page-number {
    display: none;
}
```
Let me simply remove it.

**Comment by mdosch** [comment]
That did the trick. Thank you. ☺
