### ISSUE TITLE
Disqus comments don't load

### ISSUE THREAD

**Issue by OscarLane** [carsonip/hugo-theme-minos#16]
Hi, I've changed the disqus shortname in config.toml, but comments won't load (even if they do in other themes). Is there something I'm missing? Thanks!

**Comment by SDavey149** [comment]
Put the variable disqusShortname in the params and the upper section like following for a quick hack:

```
theme = "minos"
disqusShortname = "merge-conflict"

[params]
    disqusShortname = "merge-conflict"
```

The theme is using the one in params while hugos internal disqus tempate uses the other one. Of course, the proper way to fix this is fork the theme and change the usages of {{ Site.Params.disqusShortname }} to {{ Site.DisqusShortname }} to make it consistent.

EDIT: PR created with changes to fix this https://github.com/carsonip/hugo-theme-minos/pull/24

**Comment by carsonip** [comment]
Fixed. Thank @SDavey149 for the PR!
