### ISSUE TITLE
No trailing slash in baseURL causes CSS issue

### ISSUE THREAD

**Issue by zwbetz-gh** [carsonip/hugo-theme-minos#18]
When a user does not append a trailing slash to their `baseURL` config setting, one of the theme's CSS links breaks. This is because line 15 in `layouts/partials/head.html` does not have a slash (`/`) between `{{ .Site.BaseURL }}` and `css/style.css`.

I see two ways to remedy this.

1) Update the theme's docs to say to always add a trailing slash to the `baseURL` value
2) Update the CSS links to use `absURL` instead of `{{ .Site.BaseURL }}`, this way it does not matter if the user's `baseURL` has a trailing slash or not (I recommend this way)

For example:

```
<link href="{{ "webfonts/ptserif/main.css" | absURL }}" rel='stylesheet' type='text/css'>
<link href="{{ "webfonts/source-code-pro/main.css" | absURL }}" rel="stylesheet" type="text/css">

<link rel="stylesheet" href="{{ "css/style.css" | absURL }}">
```

See below discussion for the initial report of the issue:
https://discourse.gohugo.io/t/solved-beginner-question-missing-css-or-wrong-baseurl-on-gitlab-pages/15307/3

**Comment by carsonip** [comment]
I not actively maintaining this project. Feel free to submit a PR. I'm sure you already know the fix. Thanks!
