### ISSUE TITLE
Mixed Content in the Minos theme demo on the Hugo website 

### ISSUE THREAD

**Issue by onedrawingperday** [carsonip/hugo-theme-minos#23]
Hello @carsonip  I am one of the maintainers of the Hugo Themes repository.

Recently I [reviewed](https://github.com/gohugoio/hugoThemes/issues/532#issuecomment-455900414) the deploy log of the Hugo Themes website and apparently [line 17](https://github.com/carsonip/hugo-theme-minos/blob/2a4e4032f16c5cd11c518c3773db0c0e745bac33/layouts/partials/head.html#L17) of your theme's header partial causes a  [Mixed Content](https://developer.mozilla.org/en-US/docs/Web/Security/Mixed_content) browser warning on the Hugo website because it references an insecure URL. The Hugo website is served under `HTTPS`.

To fix this warning either change [line 17](https://github.com/carsonip/hugo-theme-minos/blob/2a4e4032f16c5cd11c518c3773db0c0e745bac33/layouts/partials/head.html#L17) of the header partial to `<link href="https://gmpg.org/xfn/11" rel="profile">` or delete it, if it's no longer needed. (I notified the author of the Hugo Octopress Theme earlier about the exact same line of code and he determined that this is [no longer needed](https://github.com/parsiya/Hugo-Octopress/commit/73f38066f611cc0751eb8278aa40d7d5e3440cd3#diff-8ab16b2cae0b26a574b75e8e5c19e378L4))

Once you do the above please let me know.

Thanks

**Comment by carsonip** [comment]
Thanks for the issue. I don't really remember what it does so I have also deleted it.
