### ISSUE TITLE
Numbered list with more than 10 elements is not shown correctly

### ISSUE THREAD

**Issue by kamilwylegala** [carsonip/hugo-theme-minos#29]
Hey,

I found an issue with template when I render numbered list with more than nine elements.

E.g.
```
1. Element 1
...
9. Element 9
10. Element 10
```
It will be rendered as:

1\. Element 1
9\. Element 9
0\. Element 10

I think `entry ol { margin: 20px }` needs to be extended. Due to part of number of element is hidden.

Please confirm. I can create pull request.

Thanks!

**Comment by carsonip** [comment]
Thanks for the issue. If you have confirmed the cause and the fix, feel free to create a PR. I'll confirm there.

**Comment by carsonip** [comment]
Fixed via #30
