### ISSUE TITLE
how to service 'categories', 'tags', 'archives' and 'search'

### ISSUE THREAD

**Issue by iamnoweaver** [carsonip/hugo-theme-minos#31]
I am a rookie both Hugo and HTML/CSS for the static blog. I saw your blog screenshot image. So, I installed your theme. However, I don't know how to service 'categories', 'tags', 'archives' and 'search' on the HEADER.
Could you help me?

**Comment by iamnoweaver** [comment]
> I am a rookie both Hugo and HTML/CSS for the static blog. I saw your blog screenshot image. So, I installed your theme. However, I don't know how to service 'categories', 'tags', 'archives' and 'search' on the HEADER.
> Could you help me?

I resolved except for archives and search service.

**Comment by noweaver** [comment]
Plus, how to service the 'about' page? It's difficult to deploy Hugo to github.io
