### ISSUE TITLE
I want to know about Kerning size

### ISSUE THREAD

**Issue by iamnoweaver** [carsonip/hugo-theme-minos#33]
I am Korean. I am using Korea in my blog. The Kerning of Minos theme to use Korean is very narrow. I know the CSS, which are 'letter-spacing', 'word-spacing'. But I don't know which file to modify. 

Please show me~

**Comment by carsonip** [comment]
Hi @noweaver, sorry for the late reply. The css to be modified should be `static/css/style.css` under the theme folder in your blog.
