### ISSUE TITLE
Custom CSS?

### ISSUE THREAD

**Issue by ankush981** [carsonip/hugo-theme-minos#36]
Hello, thanks for the theme! is it possible to easily add custom CSS? I don't want to mess with the theme's Git repo as I might lose changes when I upgrade or just carelessly delete later.

**Comment by carsonip** [comment]
I didn't check the code but I don't think there is currently a way to do this. Feel free to check other themes if they have this feature, if so, we could implement it in a similar fashion.

**Comment by ankush981** [comment]
I'm new to Go and Hugo overall so can't say I know themes that do this. However, I came across [this](https://discourse.gohugo.io/t/how-to-override-css-classes-with-hugo/3033/3) discussion that shows a possible simple way out:


![image](https://user-images.githubusercontent.com/4169691/69897523-2fa91b80-1373-11ea-9b89-55d0a18edfef.png)

Do you think something like this can be done?

**Comment by carsonip** [comment]
Thanks for attaching the discussion thread. I used "customCss" as the param name for consistency. Please let me know if it works for you.

**Comment by ankush981** [comment]
Yes! Works and thanks a lot for the effort! :smile: I'm sorry I wasn't able to check this earlier and respond to you.
