### ISSUE TITLE
Theme demo is broken on the Hugo Themes Site

### ISSUE THREAD

**Issue by onedrawingperday** [carsonip/hugo-theme-minos#37]
Hello @carsonip 

It seems that commit https://github.com/carsonip/hugo-theme-minos/commit/95686c0326844bcd333cf0c209059e7360308ec9 broke your theme:

```
9:53:44 AM:  ==== PROCESSING  hugo-theme-minos  ======
9:53:45 AM: Building site for theme hugo-theme-minos using config "/opt/build/repo/_script/hugoThemeSite/config-hugo-theme-minos.toml" to ../themeSite/static/theme/hugo-theme-minos/
9:53:45 AM: Error: Error building site: failed to render pages: render of "taxonomy" failed: "/opt/build/repo/hugo-theme-minos/layouts/taxonomy/tag.html:7:60": execute of template failed: template: taxonomy/tag.html:1:3: executing "taxonomy/tag.html" at <partial "head.html" .>: error calling partial: "/opt/build/repo/hugo-theme-minos/layouts/partials/head.html:7:60": execute of template failed: template: partials/head.html:6:7: executing "partials/head.html" at <partial "meta.html" .>: error calling partial: "/opt/build/repo/hugo-theme-minos/layouts/partials/meta.html:7:60": execute of template failed: template: partials/meta.html:7:60: executing "partials/meta.html" at <$author>: range can't iterate over Hugo
9:53:45 AM: FAILED to create demo site for hugo-theme-minos
```
Please look at it and let me know.

Thanks

**Comment by carsonip** [comment]
Cannot reproduce the issue. I am using https://github.com/gohugoio/HugoBasicExample and hugo version `Hugo Static Site Generator v0.54.0-B1A82C61 linux/amd64 BuildDate: 2019-02-01T09:40:34Z` I also tried v0.60.1, no issue.

May I know your Hugo version and the test site you are using?

**Comment by onedrawingperday** [comment]
I am one of the maintainers of https://themes.gohugo.io/ and the above quote is from the [latest deploy log](https://app.netlify.com/sites/hugothemes/deploys/5de30868eb71800008d86712) of the Hugo Themes website on Netlify.

The website uses the latest Hugo i.e. v.0.60.1

**Comment by carsonip** [comment]
I acknowledge that you are a maintainer and thanks for maintaining the themes site. I thought hugo themes site uses https://github.com/gohugoio/HugoBasicExample but I didn't find any errors with it and 0.60.1 locally.

**Comment by carsonip** [comment]
Although I cannot reproduce it locally, I am looking into the issue right now, please give me some time.

**Comment by onedrawingperday** [comment]
You have plenty of time.

Also have a look at the instructions for testing the theme site locally: https://github.com/gohugoio/hugoThemes#testing-a-theme-with-the-hugo-themes-website-build-script

**Comment by onedrawingperday** [comment]
If line 7 of `partials/meta.html` is changed to:
`{{ if $author -}} <meta name="author" content="{{ $author }}"> {{- end }`

Then the theme demo will generate with the Hugo Themes build script.

You do not provide any sample config in your theme.
The inherited `author` parameter from the Hugo Basic Example [is a string](https://github.com/gohugoio/hugoBasicExample/blob/master/config.toml#L3)
You cannot use the `range` function over a string.
Hence the ERROR.

**Comment by carsonip** [comment]
I am looking at the same line. However `.Site.Params.Author` should be empty since the author variable in basic example is mapped to `.Site.Author`. Somehow in theme example site generation the config `.Site.Params.Author` is non-empty and is a string.

Anyway, I am looking at doing:
```
    {{ with .Site.Params.Author -}}<meta name="author" content="{{ . }}">{{- end }}
```

Just ignore .Site.Author and use Params instead.

**Comment by onedrawingperday** [comment]
@carsonip 

I have updated your theme and its demo is now published again on the Hugo Themes website:
https://themes.gohugo.io/hugo-theme-minos/

Thank you for issuing a fix so quickly.
