### ISSUE TITLE
No toc for posts in asciidoc format

### ISSUE THREAD

**Issue by kaifeng** [carsonip/hugo-theme-minos#38]
Hi, I am using asciidoc as the content format, the toc doesn't show up for *.adoc but works for markdown, is there any option to turn this on or it's just unimplemented? Thanks!

**Comment by carsonip** [comment]
I suppose it works for adoc too. Didn't write anything specific to md. Make sure you have smartToc param enabled in site / post. https://github.com/carsonip/hugo-theme-minos#smart-toc
The `[params]` is necessary as far as I remember.

**Comment by kaifeng** [comment]
Yes, smartToc is enabled. If there no special handling in the template, I guess this is the limit lies in the hugo because it calls external tools to generate html while markdown is natively supported :(
Anyway, thanks for your reply.

**Comment by carsonip** [comment]
Not sure what's going on here, but please let me know if you have any updates.

**Comment by carsonip** [comment]
Is #40 related?

**Comment by carsonip** [comment]
Do you find the TOC components in the generated html source?

**Comment by kaifeng** [comment]
I am not familiar with frontend area, but I think I didn't find toc generated, either with smartToc enabled or not, in case of asciidoc.

**Comment by carsonip** [comment]
I just tried asciidoctor, and realize that no article-toc is generated. This is an open hugo issue: https://github.com/gohugoio/hugo/issues/1687

I'll close this issue for now.
