### ISSUE TITLE
TOC not showing after setting smartToc to true

### ISSUE THREAD

**Issue by caseneuve** [carsonip/hugo-theme-minos#40]
Adding 
```toml
[params]
  smartToc = true
```
to config has no effect. I had to delete [this line](https://github.com/carsonip/hugo-theme-minos/blob/master/static/css/style.css#L677) and change logic [here](https://github.com/carsonip/hugo-theme-minos/blob/master/layouts/partials/article.html#L39) to:
```html
<div class="article-toc" {{if not .Site.Params.SmartToc }} style="display:none;" {{end}}>
```
to make it work as intended. Is the TOC showing in your original setup?

**Comment by carsonip** [comment]
I wrote that code 3 years ago but as far as I remember, there's a difference between a normal TOC and a smart TOC. The only issue here is that whether the normal TOC should be disabled when smart TOC is on. I'll need to take a look into it.

**Comment by carsonip** [comment]
It works in my setup. Smart TOC works on top of normal TOC. It relies on JavaScript to work. It uses `document.getElementsByClassName('article-toc')[0].style.display = '';` to offset the display none toggle. Therefore please make sure JavaScript is enabled in your browser.

**Comment by carsonip** [comment]
Example config.toml:
```
baseURL = "http://example.org/"
languageCode = "en-us"
title = "My New Hugo Site"
theme = "hugo-theme-minos"
[params]
    smartToc = true
```

Example article a.md (just a random long article to demo "smart" TOC):
```
---
title: "Hi"
date: 2017-08-11T11:53:52+08:00
---

# H1
sd

f

asdf

asdf

df
sdf

sdf

sdf

sd

d
d
d
d

d
d



d
d

d

d


## h2

asdf

d
d

d

d

d




d

d

d
d
d



d
d

d

asdf
asdf

## h4

asd
sdf
sdf

sdf


sdf
sdf
sdf

sdf
sdf

sdf

sdf
sdf

sdf

sdf

sdf
sdf


## H2
444
d

d

d
d



d
d

d
d
d


d
d

d

d
d

d
d

d

```

**Comment by caseneuve** [comment]
I'm sorry I haven't answered earlier. Thanks for all your answers. I checked the behavior on different browsers (namely qutebrowser and Firefox) with js enabled and got some random effects (sometimes ToC was shown, sometimes not) On the other hand my 'hack' is working, so I'd stick with that. Since I can't find the source of the problem I'm leaving the issue as it is.

**Comment by carsonip** [comment]
It could be related to browser viewport size, i.e. the toc will hide under mobile browsers, or due to other weird reasons. If smartToc doesn't work for you, try the normal TOC.
