### ISSUE TITLE
google analytics setting in config

### ISSUE THREAD

**Issue by michaeldesu** [carsonip/hugo-theme-minos#41]
In the readme here and on hugo's site, the GA setup is quoted as so

```
[params]
    googleAnalytics = "UA-123-45"
```
but it will result in the GA code not being inserted. The doc should be updated to be simply: 

```
googleAnalytics = "UA-123-45"
```

which is consistent with other theme's doc.

**Comment by carsonip** [comment]
You're right. I've updated the README. Thanks!
