### ISSUE TITLE
.Now will be deprecated with Hugo v0.20

### ISSUE THREAD

**Issue by digitalcraftsman** [carsonip/hugo-theme-minos#6]
`.Now` will be deprecated replaced with the `now` template function in Hugo v0.20 which eventually will be released on Monday. It's likely that the deprecation will cause builds to fail.

**Comment by carsonip** [comment]
Thanks @digitalcraftsman. I noticed that this is not backward compatible tho. I have therefore updated the min version of hugo to 0.20.

**Comment by digitalcraftsman** [comment]
Thanks for the update @carsonip 

> I noticed that this is not backward compatible tho

That's usually a the consequence of a deprecation :wink: But I did the same with my themes
